version: "3.7"
services:
  frontend:
    build: frontend
    ports:
      - 3000:3000
    container_name: frontend
    stdin_open: true
    restart: always
    networks:
    - react-express
    depends_on:
    - backend
  
  backend:
    container_name: backend
    restart: always
    build: backend
    ports:
    - 3001:3001
    depends_on:
    - redis
    networks:
    - react-express
    - express-redis

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    networks:
    - express-redis

networks:
  react-express:
  express-redis:
